// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDZWz2jLwLyxJAgdoHLt8r94Z4_JeNVT5M',
    appId: '1:45881835603:web:3c590140121646bbbb46a6',
    messagingSenderId: '45881835603',
    projectId: 'authapp1990',
    authDomain: 'authapp1990.firebaseapp.com',
    databaseURL: 'https://authapp1990-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'authapp1990.appspot.com',
    measurementId: 'G-BT78QPDCNL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCQec_2gnP9m1ddfqJkJ8UK0Ww2r6nPWmY',
    appId: '1:45881835603:android:a9ef74702c05ecd3bb46a6',
    messagingSenderId: '45881835603',
    projectId: 'authapp1990',
    databaseURL: 'https://authapp1990-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'authapp1990.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDvJeBMB59cRKJWbxdkuDeOXdcD8I9YS64',
    appId: '1:45881835603:ios:eee530bae7262eb0bb46a6',
    messagingSenderId: '45881835603',
    projectId: 'authapp1990',
    databaseURL: 'https://authapp1990-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'authapp1990.appspot.com',
    iosBundleId: 'com.example.authenticationApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDvJeBMB59cRKJWbxdkuDeOXdcD8I9YS64',
    appId: '1:45881835603:ios:dfb0f55ee7f4fb61bb46a6',
    messagingSenderId: '45881835603',
    projectId: 'authapp1990',
    databaseURL: 'https://authapp1990-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'authapp1990.appspot.com',
    iosBundleId: 'com.example.authenticationApp.RunnerTests',
  );
}
